default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: trivia_duel
  username: lilykerr
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

test:
  <<: *default
  database: trivia_duel_test
  username: lilykerr
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
